import {useState} from "react"
import {Link, useLocation, useNavigate} from "react-router-dom"
import {api} from "../services/api"

export default function ResetPasswordPage() {
  const navigate = useNavigate()
  const location = useLocation()
  const [token, setToken] = useState(location.state?.token || "")
  const [newPassword, setNewPassword] = useState("")
  const [message, setMessage] = useState("")
  const [isError, setIsError] = useState(false)
  const [isSubmitting, setIsSubmitting] = useState(false)
  const canResetPassword = token.trim().length > 0 && newPassword.trim().length > 0

  const handleSubmit = async (event) => {
    event.preventDefault()
    if (!canResetPassword || isSubmitting) {
      return
    }
    setMessage("")
    setIsError(false)
    setIsSubmitting(true)

    try {
      await api.post("/doctors/password-reset/confirm", {
        token,
        new_password: newPassword,
      })

      navigate("/login", {
        state: {
          message: "Password reset successfully. Sign in with your new password.",
        },
      })
    } catch (error) {
      setIsError(true)
      setMessage(error.response?.data?.detail || ("Unable to reset password."))
    } finally {
      setIsSubmitting(false)
    }
  }

  return (
    <div className="app-shell login-page login-page-centered">
      <div className="login-card monitor-card">
        <div className="login-layout">
          <aside className="login-aside">
            <div className="flex items-center justify-between gap-3">
              <p className="login-brand">MedStream Console</p>
              <Link className="auth-link" to="/">
                {"Back home"}
              </Link>
            </div>
            <h1 className="login-title">{"Reset Doctor Password"}</h1>
            <p className="login-subtitle">{"Complete the recovery flow using the reset token generated by the forgot-password request."}</p>
            <div className="auth-metrics">
              <div className="auth-metric">
                <p className="auth-metric-label">Token</p>
                <p className="auth-metric-value">One-time reset value</p>
                <p className="auth-metric-copy">Paste the token exactly as issued by the password reset request flow.</p>
              </div>
              <div className="auth-metric">
                <p className="auth-metric-label">Security</p>
                <p className="auth-metric-value">New password required</p>
                <p className="auth-metric-copy">A successful reset invalidates the token and stores a new password hash.</p>
              </div>
            </div>
          </aside>

          <div className="auth-divider" aria-hidden="true"/>
          <div className="hidden lg:block w-px bg-[#2a3441] mx-6" />

          <div className="login-panel">
            <div className="login-header">
              <p className="login-brand">{"Recovery"}</p>
              <h1 className="login-title">{"Reset Password"}</h1>
              <p className="login-subtitle">{"Enter the reset token and choose a new password."}</p>
            </div>

            <form className="login-form" onSubmit={handleSubmit}>
              <div className="login-field">
                <label className="login-label" htmlFor="token">
                  {"Reset Token"}
                </label>
                <input
                  id="token"
                  type="text"
                  value={token}
                  onChange={(event) => setToken(event.target.value)}
                  className="login-input"
                  placeholder={"Example: paste reset token"}
                  required
                />
              </div>

              <div className="login-field">
                <label className="login-label" htmlFor="new_password">
                  {"New Password"}
                </label>
                <input
                  id="new_password"
                  type="password"
                  value={newPassword}
                  onChange={(event) => setNewPassword(event.target.value)}
                  className="login-input"
                  placeholder={"Example: MedstreamSecure123"}
                  required
                />
              </div>

              {message && (
                <p className={isError ? "login-error" : "login-success"}>
                  {message}
                </p>
              )}

              <div className="auth-actions">
                <button
                  type="submit"
                  disabled={!canResetPassword || isSubmitting}
                  className="login-button"
                >
                  {isSubmitting ? ("Resetting...") : ("Reset Password")}
                </button>

                <div className="flex items-center justify-between gap-3 text-sm">
                  <Link className="auth-link" to="/forgot-password">
                    {"Request another token"}
                  </Link>
                  <Link className="auth-link" to="/login">
                    {"Back to login"}
                  </Link>
                </div>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  )
}
